### ISSUE TITLE
Create a way to migrate or bootstrap

### ISSUE THREAD

**Issue by bcmackintosh** [TeamHG-Memex/agnostic#3]
I'm currently using agnostic in a bash run script, where the database can exist from previous versions, and means the database can be in one of 3 states:
1 It is a fresh installation, and the database will be created and agnostic will be bootstrapped.
2 The database is already created, but agnostic has not been bootstrapped.
3 The database is created and agnostic has been bootstrapped.

Dealing with cases 2 and 3 are awkward, because I need to catch the error thrown by agnostic, and parse the message to see if agnostic needs to run `bootstrap` or `migrate`.

It would be nice if there were some way to run migrations which would fallback to bootstrapping with agnostic.  At the very least a silent run option would be nice, where I could run both bootstrap and then migrate, and ignore all errors.

**Comment by mehaase** [comment]
I don't totally understand the problem, but I'll list a few solutions that popped into my head. Maybe discussing these will help me understand your use case better.

1. I don't think there's any harm in running bootstrap on a system that's already bootstrapped. You could just always run `agnostic bootstrap && agnostic migrate` right?
2. The exit code of `agnostic bootstrap` should be non-zero if bootstrapping fails. Could you use the exit code, like `agnostic bootstrap || agnostic migrate`? (You can also use the exit code as a condition in an `if` block for more complicated logic.)
3. In my projects where I'm using agnostic, we always have some way of knowing the state of the system (whether we are installing fresh or upgrading). For example, you could touch a specific file after deployment. If the script sees that file exists, it knows that it should run in upgrade mode. (I'll send you an example from a private repo.)
4. If we go down the route of adding a new feature to Agnostic, it sounds like you're asking for an `agnostic auto` command? Where `auto` means to bootstrap if it hasn't been bootstrapped, otherwise run migrations?

> It would be nice if there were some way to run migrations which would fallback to bootstrapping with agnostic. At the very least a silent run option would be nice, where I could run both bootstrap and then migrate, and ignore all errors.

How about `agnostic bootstrap 2>&1 >/dev/null`?

**Comment by bcmackintosh** [comment]
I ended up putting in a check for the database using `mysqlshow`.  If no database exists, it builds the database and runs `agnostic bootstrap`.  If the database exists, it simply runs `agnostic bootstrap &> /dev/null` then `agnostic migrate`.

This solution and the other solutions above seem to be fine.  It'd be great to add documentation for new users in the same boat I was, so they have some approved methods of dealing with the problem.

I'll go ahead and close this issue.

**Comment by bcmackintosh** [comment]
A quick addendum to this after attempting to deploy.  Make sure to run `bootstrap` with the `--no-load-existing` arg before running `migrate`.
