### ISSUE TITLE
No database password

### ISSUE THREAD

**Issue by ThibaudDauce** [TeamHG-Memex/agnostic#5]
Hi,

Is it possible to run the migration on a database without password? Is seems to be a requirement and I couldn't find a way to pass an empty string…

Thanks

**Comment by mehaase** [comment]
That's a good question. I've never tried using Agnostic on a database without a password. To pass an empty string, you could do one of the following:

    agnostic --password "" ...

Or

    export AGNOSTIC_PASSWORD=""
    agnostic ...

Or you could run Agnostic without a password and type <Enter> when it prompts for a password.

Will you let me know if any of these works for you? Otherwise I'll need to make password an optional argument, which will require uploading a new release.

**Comment by ThibaudDauce** [comment]
Hi,

I've already try these solutions. None of them work ^^

I solved the problem by editing the main source file and setting a default password as an empty string.
```
@click.option(
    '--password',
    default='',
    envvar='AGNOSTIC_PASSWORD',
    metavar='<pass>',
    required=True,
    prompt='Database password',
    hide_input=True,
    help='Database password. If omitted, the password must be entered on stdin.'
)
```

I can submit a PR if you want.

**Comment by mehaase** [comment]
A PR would be nice, thank you!
